In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://www.worldometers.info/world-population/nigeria-population/#:~:text=The%20current%20population%20of%20Nigeria,latest%20United%20Nations%20data%201."
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

In [6]:
table = soup.find('table', class_='table table-striped table-bordered table-hover table-condensed table-list')

In [7]:
table_rows = table.find_all('tr')

In [8]:
header_row = table.find('thead').find_all('th')
header_names = [header.text.strip() for header in header_row]
header_names

['Year',
 'Population',
 'Yearly %  Change',
 'Yearly Change',
 'Migrants (net)',
 'Median Age',
 'Fertility Rate',
 'Density (P/Km²)',
 'Urban Pop %',
 'Urban Population',
 "Country's Share of World Pop",
 'World Population',
 'NigeriaGlobal Rank']

In [9]:
hh = []
for header in header_row:
    he = header.text.strip()
    hh.append(he)
    
    
hh

['Year',
 'Population',
 'Yearly %  Change',
 'Yearly Change',
 'Migrants (net)',
 'Median Age',
 'Fertility Rate',
 'Density (P/Km²)',
 'Urban Pop %',
 'Urban Population',
 "Country's Share of World Pop",
 'World Population',
 'NigeriaGlobal Rank']

In [10]:
data = []
for row in table.find_all('tr'):
    row_data = [cell.text.strip() for cell in row.find_all('td')]
    data.append(row_data)
    
    
data

[[],
 ['2024',
  '229,152,217',
  '2.39 %',
  '5,347,585',
  '-59,996',
  '17.4',
  '4.99',
  '252',
  '54.7 %',
  '125,447,884',
  '2.82 %',
  '8,118,835,999',
  '6'],
 ['2023',
  '223,804,632',
  '2.41 %',
  '5,263,420',
  '-59,996',
  '17.2',
  '5.06',
  '246',
  '53.9 %',
  '120,696,717',
  '2.78 %',
  '8,045,311,447',
  '6'],
 ['2022',
  '218,541,212',
  '2.41 %',
  '5,139,889',
  '-59,996',
  '17.1',
  '5.14',
  '240',
  '53.1 %',
  '116,057,853',
  '2.74 %',
  '7,975,105,156',
  '6'],
 ['2020',
  '208,327,405',
  '2.47 %',
  '5,022,913',
  '-4,824',
  '16.9',
  '5.31',
  '229',
  '51.4 %',
  '107,112,526',
  '2.66 %',
  '7,840,952,880',
  '7'],
 ['2015',
  '183,995,785',
  '2.71 %',
  '4,608,586',
  '-145,917',
  '16.7',
  '5.62',
  '202',
  '47.1 %',
  '86,673,094',
  '2.48 %',
  '7,426,597,537',
  '7'],
 ['2010',
  '160,952,853',
  '2.76 %',
  '4,092,426',
  '18,073',
  '16.7',
  '5.98',
  '177',
  '42.8 %',
  '68,949,828',
  '2.30 %',
  '6,985,603,105',
  '7'],
 ['2005',
  '140,490,722',
  '2.72 %',
  '3,527,748',
  '-46,749',
  '17.0',
  '6.07',
  '154',
  '38.6 %',
  '54,288,918',
  '2.14 %',
  '6,558,176,119',
  '9'],
 ['2000',
  '122,851,984',
  '2.57 %',
  '2,932,875',
  '34,146',
  '17.0',
  '6.12',
  '135',
  '34.7 %',
  '42,627,440',
  '2.00 %',
  '6,148,898,975',
  '10'],
 ['1995',
  '108,187,610',
  '2.59 %',
  '2,594,671',
  '43,504',
  '16.7',
  '6.27',
  '119',
  '32.2 %',
  '34,785,545',
  '1.88 %',
  '5,743,219,454',
  '10'],
 ['1990',
  '95,214,257',
  '2.64 %',
  '2,325,801',
  '107,212',
  '16.4',
  '6.46',
  '105',
  '29.7 %',
  '28,276,132',
  '1.79 %',
  '5,316,175,862',
  '10'],
 ['1985',
  '83,585,251',
  '2.76 %',
  '2,126,762',
  '19,791',
  '16.5',
  '6.62',
  '92',
  '25.6 %',
  '21,434,266',
  '1.72 %',
  '4,861,730,613',
  '10'],
 ['1980',
  '72,951,439',
  '3.03 %',
  '2,020,025',
  '184,467',
  '17.0',
  '6.85',
  '80',
  '22.1 %',
  '16,139,321',
  '1.64 %',
  '4,444,007,706',
  '11'],
 ['1975',
  '62,851,312',
  '2.49 %',
  '1,456,410',
  '75,448',
  '17.5',
  '6.77',
  '69',
  '19.9 %',
  '12,535,584',
  '1.54 %',
  '4,069,437,231',
  '11'],
 ['1970',
  '55,569,264',
  '2.16 %',
  '1,128,693',
  '7,960',
  '18.0',
  '6.47',
  '61',
  '17.9 %',
  '9,942,297',
  '1.50 %',
  '3,695,390,336',
  '12'],
 ['1965',
  '49,925,799',
  '2.13 %',
  '999,491',
  '28,207',
  '18.3',
  '6.37',
  '55',
  '16.6 %',
  '8,296,771',
  '1.50 %',
  '3,337,111,983',
  '14'],
 ['1960',
  '44,928,342',
  '1.93 %',
  '817,824',
  '12,174',
  '18.3',
  '6.36',
  '49',
  '15.5 %',
  '6,955,737',
  '1.49 %',
  '3,019,233,434',
  '14'],
 ['1955',
  '40,839,223',
  '1.89 %',
  '729,971',
  '-12,619',
  '18.3',
  '6.40',
  '45',
  '12.1 %',
  '4,952,844',
  '1.49 %',
  '2,746,072,141',
  '14']]

In [11]:
df = pd.DataFrame(data, columns=header_names)
df

,Year,Population,Yearly % Change,Yearly Change,Migrants (net),Median Age,Fertility Rate,Density (P/Km²),Urban Pop %,Urban Population,Country's Share of World Pop,World Population,NigeriaGlobal Rank
0,None,None,None,None,None,None,None,None,None,None,None,None,None
1,2024,"229,152,217",2.39 %,"5,347,585","-59,996",17.4,4.99,252,54.7 %,"125,447,884",2.82 %,"8,118,835,999",6
2,2023,"223,804,632",2.41 %,"5,263,420","-59,996",17.2,5.06,246,53.9 %,"120,696,717",2.78 %,"8,045,311,447",6
3,2022,"218,541,212",2.41 %,"5,139,889","-59,996",17.1,5.14,240,53.1 %,"116,057,853",2.74 %,"7,975,105,156",6
4,2020,"208,327,405",2.47 %,"5,022,913","-4,824",16.9,5.31,229,51.4 %,"107,112,526",2.66 %,"7,840,952,880",7
5,2015,"183,995,785",2.71 %,"4,608,586","-145,917",16.7,5.62,202,47.1 %,"86,673,094",2.48 %,"7,426,597,537",7
6,2010,"160,952,853",2.76 %,"4,092,426","18,073",16.7,5.98,177,42.8 %,"68,949,828",2.30 %,"6,985,603,105",7
7,2005,"140,490,722",2.72 %,"3,527,748","-46,749",17.0,6.07,154,38.6 %,"54,288,918",2.14 %,"6,558,176,119",9
8,2000,"122,851,984",2.57 %,"2,932,875","34,146",17.0,6.12,135,34.7 %,"42,627,440",2.00 %,"6,148,898,975",10
9,1995,"108,187,610",2.59 %,"2,594,671","43,504",16.7,6.27,119,32.2 %,"34,785,545",1.88 %,"5,743,219,454",10
10,1990,"95,214,257",2.64 %,"2,325,801","107,212",16.4,6.46,105,29.7 %,"28,276,132",1.79 %,"5,316,175,862",10
11,1985,"83,585,251",2.76 %,"2,126,762","19,791",16.5,6.62,92,25.6 %,"21,434,266",1.72 %,"4,861,730,613",10
12,1980,"72,951,439",3.03 %,"2,020,025","184,467",17.0,6.85,80,22.1 %,"16,139,321",1.64 %,"4,444,007,706",11
13,1975,"62,851,312",2.49 %,"1,456,410","75,448",17.5,6.77,69,19.9 %,"12,535,584",1.54 %,"4,069,437,231",11
14,1970,"55,569,264",2.16 %,"1,128,693","7,960",18.0,6.47,61,17.9 %,"9,942,297",1.50 %,"3,695,390,336",12
15,1965,"49,925,799",2.13 %,"999,491","28,207",18.3,6.37,55,16.6 %,"8,296,771",1.50 %,"3,337,111,983",14
16,1960,"44,928,342",1.93 %,"817,824","12,174",18.3,6.36,49,15.5 %,"6,955,737",1.49 %,"3,019,233,434",14
17,1955,"40,839,223",1.89 %,"729,971","-12,619",18.3,6.40,45,12.1 %,"4,952,844",1.49 %,"2,746,072,141",14

In [15]:
from sqlalchemy import create_engine

db_params = {
    "dbname":"population_etl",
    "user": "postgres",
    "password":"Psalms121",
    "host":"localhost",
    "port":"5432"
}

# Create SQLAlchemy engine
engine = create_engine(f'postgresql://{db_params["user"]}:{db_params["password"]}@{db_params["host"]}:{db_params["port"]}/{db_params["dbname"]}')
print('SQL Engine Connected Successfully')

SQL Engine Connected Successfully

In [18]:
df.to_sql("Population_of_Nigeria_2024_Below", engine, if_exists='replace', index=False)

print("DataFrame Successfully written")

DataFrame Successfully written